name: Deploy EV Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Frontend
      - uses: docker/build-push-action@v6
        with:
          context: ./EV-Service-Center-Full/frontend
          file: ./EV-Service-Center-Full/frontend/dockerfile
          push: true
          tags: lequangm/frontend:latest

      # API Gateway
      - uses: docker/build-push-action@v6
        with:
          context: ./EV-Service-Center-Full/api-gateway
          file: ./EV-Service-Center-Full/api-gateway/Dockerfile
          push: true
          tags: lequangm/api-gateway:latest

      # User Service
      - uses: docker/build-push-action@v6
        with:
          context: ./EV-Service-Center-Full/services/user-service
          file: ./EV-Service-Center-Full/services/user-service/Dockerfile
          push: true
          tags: lequangm/user-service:latest

      # Inventory Service
      - uses: docker/build-push-action@v6
        with:
          context: ./EV-Service-Center-Full/services/inventory-service
          file: ./EV-Service-Center-Full/services/inventory-service/Dockerfile
          push: true
          tags: lequangm/inventory-service:latest

      # Booking Service
      - uses: docker/build-push-action@v6
        with:
          context: ./EV-Service-Center-Full/services/booking-service
          file: ./EV-Service-Center-Full/services/booking-service/Dockerfile
          push: true
          tags: lequangm/booking-service:latest

      # Finance Service
      - uses: docker/build-push-action@v6
        with:
          context: ./EV-Service-Center-Full/services/finance-service
          file: ./EV-Service-Center-Full/services/finance-service/Dockerfile
          push: true
          tags: lequangm/finance-service:latest

      # Maintenance Service
      - uses: docker/build-push-action@v6
        with:
          context: ./EV-Service-Center-Full/services/maintenance-service
          file: ./EV-Service-Center-Full/services/maintenance-service/Dockerfile
          push: true
          tags: lequangm/maintenance-service:latest

      # Payment Service
      - uses: docker/build-push-action@v6
        with:
          context: ./EV-Service-Center-Full/services/payment-service
          file: ./EV-Service-Center-Full/services/payment-service/Dockerfile
          push: true
          tags: lequangm/payment-service:latest

      # Notification Service
      - uses: docker/build-push-action@v6
        with:
          context: ./EV-Service-Center-Full/services/notification-service
          file: ./EV-Service-Center-Full/services/notification-service/Dockerfile
          push: true
          tags: lequangm/notification-service:latest

      # Report Service
      - uses: docker/build-push-action@v6
        with:
          context: ./EV-Service-Center-Full/services/report-service
          file: ./EV-Service-Center-Full/services/report-service/Dockerfile
          push: true
          tags: lequangm/report-service:latest

      # Chat Service
      - uses: docker/build-push-action@v6
        with:
          context: ./EV-Service-Center-Full/services/chat-service
          file: ./EV-Service-Center-Full/services/chat-service/Dockerfile
          push: true
          tags: lequangm/chat-service:latest

      # Staff Service
      - uses: docker/build-push-action@v6
        with:
          context: ./EV-Service-Center-Full/services/staff-service
          file: ./EV-Service-Center-Full/services/staff-service/Dockerfile
          push: true
          tags: lequangm/staff-service:latest

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/DTDM-EV-Service/EV-Service-Center-Full
            git pull origin main
            docker compose pull
            docker compose up -d --remove-orphans